[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pg"]
  included_files = [
    "netlify/lib/**",
    "src/data/**",
    "node_modules/pg/**",
    "node_modules/buffer-writer/**",
    "node_modules/packet-reader/**",
    "node_modules/pg-connection-string/**",
    "node_modules/pg-pool/**",
    "node_modules/pg-protocol/**",
    "node_modules/pg-types/**",
    "node_modules/pgpass/**",
    "node_modules/pg-int8/**",
    "node_modules/postgres-array/**",
    "node_modules/postgres-bytea/**",
    "node_modules/postgres-date/**",
    "node_modules/postgres-interval/**"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
