[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  included_files = ["src/data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
